import SwiftData
import AppKit
import Combine
import ImageIO
import os

/// Manages the clipboard history: monitors NSPasteboard, deduplicates entries,
/// enforces the max-history limit, and writes ClipEntry records to SwiftData.
///
/// Reference: `legacy/Source/ClipsController.{h,m}` and `Clip.{h,m}`.
@MainActor
final class ClipsService {
    private static let log = Logger(subsystem: "com.naotaka.ClipMenu", category: "ClipsService")
    nonisolated static let maximumTextBytes = 16 * 1024 * 1024
    nonisolated static let maximumCaptureBytes = 64 * 1024 * 1024
    nonisolated static let maximumItemCount = 1_024
    nonisolated static let maximumImagePixels = 32_000_000

    /// Marker presence, including an empty payload, forbids capturing every
    /// representation of the copy. See https://nspasteboard.org/.
    static let ignoredPasteboardTypes: Set<NSPasteboard.PasteboardType> = Set([
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.RestoredType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ].map(NSPasteboard.PasteboardType.init(rawValue:)))

    private let monitor: ClipboardMonitor
    private let pasteboard: NSPasteboard
    private let exclusion  = AppExclusionService()
    private let paste      = PasteService()
    private let settings: ClipMenuSettings

    private var context:     ModelContext?
    private var cancellables = Set<AnyCancellable>()

    init(settings: ClipMenuSettings = ClipMenuSettings(), pasteboard: NSPasteboard = .general) {
        self.settings = settings
        self.pasteboard = pasteboard
        monitor = ClipboardMonitor(pasteboard: pasteboard)
    }

    func start(context: ModelContext) {
        stop()
        self.context = context
        exclusion.update(from: settings)
        enforceHistoryLimitNow()
        monitor.start()
        monitor.pasteboardChanged
            .sink { [weak self] change in
                Task {
                    await self?.handlePasteboardChange(
                        change.pasteboard,
                        expectedChangeCount: change.changeCount,
                        observedBundleIdentifier: change.sourceBundleIdentifier
                    )
                }
            }
            .store(in: &cancellables)
    }

    func stop() {
        cancellables.removeAll()
        monitor.stop()
    }

    /// Copies the given entry back onto the system pasteboard and triggers paste.
    @discardableResult
    func select(_ entry: ClipEntry, pasteImmediately: Bool = true) async -> Bool {
        let pboard = pasteboard
        guard !entry.types.isEmpty || entry.stringValue != nil else { return false }

        var declaredTypes = entry.types.map(NSPasteboard.PasteboardType.init(rawValue:))
        if declaredTypes.isEmpty {
            declaredTypes = [.string]
        }
        // URLs are one string per pasteboard item, not an array property list.
        // Keep additional text/rich representations on the first item.
        let urls = entry.filenames?.map { URL(fileURLWithPath: $0).absoluteString }
            ?? entry.urlStrings ?? []
        let urlType: NSPasteboard.PasteboardType = entry.filenames != nil ? .fileURL : .URL
        let items = (0..<max(urls.count, 1)).map { _ in NSPasteboardItem() }
        let first = items[0]
        for (item, url) in zip(items, urls) { item.setString(url, forType: urlType) }

        for type in declaredTypes {
            switch type {
            case .string:
                if let value = entry.stringValue {
                    first.setString(value, forType: .string)
                }
            case .rtfd:
                if entry.isRTFD, let data = entry.rtfData {
                    first.setData(data, forType: .rtfd)
                }
            case .rtf:
                if !entry.isRTFD, let data = entry.rtfData {
                    first.setData(data, forType: .rtf)
                }
            case .pdf:
                if let data = entry.pdfData {
                    first.setData(data, forType: .pdf)
                }
            case .fileURL, .URL:
                break // Written above, including all files in a multi-file copy.
            case .tiff, .png:
                if let data = entry.imageData {
                    // Older captures could contain PNG bytes under a TIFF type.
                    let pngSignature: [UInt8] = [137, 80, 78, 71, 13, 10, 26, 10]
                    let tiff = data.starts(with: pngSignature)
                        ? NSBitmapImageRep(data: data)?.tiffRepresentation : data
                    if let tiff { first.setData(tiff, forType: .tiff) }
                }
            default:
                break
            }
        }
        guard writeReplacingContents(items, on: pboard) else { return false }

        monitor.ignoreCurrentChange()
        // lastUsedAt marks the clip actions should use, even when the history
        // menu is shown in capture order.
        entry.lastUsedAt = .now
        if let context {
            do {
                try context.save()
            } catch {
                Self.log.error("Failed saving clip selection: \(error.localizedDescription, privacy: .private)")
            }
        }

        if pasteImmediately && settings.autoPasteAfterSelection {
            Self.log.debug("Auto-paste after clip selection is ON (immediate)")
            await paste.paste()
        } else {
            Self.log.debug("Clip selected without immediate paste (pasteImmediately=\(pasteImmediately, privacy: .public), setting=\(self.settings.autoPasteAfterSelection, privacy: .public))")
        }
        return true
    }

    func handlePasteboardChange(_ pboard: NSPasteboard, expectedChangeCount: Int? = nil,
                               observedBundleIdentifier: String? = nil) async {
        guard let clip = makeClip(from: pboard, expectedChangeCount: expectedChangeCount,
                                  observedBundleIdentifier: observedBundleIdentifier) else { return }
        guard let context else { return }

        do {
            let existing = try context.fetch(FetchDescriptor<ClipEntry>())
            let hash = clip.contentHash
            if let matched = existing.first(where: { $0.contentHash == hash && $0.hasSameContent(as: clip) }) {
                matched.lastUsedAt = .now
                if matched.imageData != nil || clip.imageData != nil {
                    Self.log.debug("Matched existing image clip")
                }
                // Actions can insert a transformed clip before the monitor
                // observes it. Enforce the limit on that duplicate path too.
                trimHistoryIfNeeded(context: context)
                try context.save()
                return
            }

            context.insert(clip)
            Self.log.debug("Captured clipboard entry")
            if clip.imageData != nil {
                Self.log.debug("Inserted image clip")
            }
            trimHistoryIfNeeded(context: context)
            try context.save()
        } catch {
            Self.log.error("Failed handling pasteboard change: \(error.localizedDescription, privacy: .private)")
            return
        }
    }

    private func enforceHistoryLimitNow() {
        guard let context else { return }
        trimHistoryIfNeeded(context: context)
        try? context.save()
    }

    private func trimHistoryIfNeeded(context: ModelContext) {
        do {
            // Offset fetches merge pending inserts AND updates separately.
            // Flush both so a new or recently used clip cannot be mistaken for
            // an entry beyond the retained range.
            if context.hasChanges { try context.save() }
            var descriptor = FetchDescriptor<ClipEntry>(sortBy: [SortDescriptor(\ClipEntry.lastUsedAt, order: .reverse)])
            descriptor.fetchOffset = max(settings.maxHistorySize, 0)
            let clips = try context.fetch(descriptor)

            for clip in clips {
                context.delete(clip)
            }
        } catch {
            Self.log.error("Failed trimming history: \(error.localizedDescription, privacy: .private)")
        }
    }

    func makeClip(from pboard: NSPasteboard, expectedChangeCount: Int? = nil,
                  observedBundleIdentifier: String? = nil) -> ClipEntry? {
        let changeCount = expectedChangeCount ?? pboard.changeCount
        guard pboard.changeCount == changeCount else { return nil }
        guard let pbTypes = pboard.types, !pbTypes.isEmpty else { return nil }
        guard Self.ignoredPasteboardTypes.isDisjoint(with: pbTypes) else { return nil }

        let items = pboard.pasteboardItems ?? []
        guard items.count <= Self.maximumItemCount,
              items.allSatisfy({ Self.ignoredPasteboardTypes.isDisjoint(with: $0.types) }) else { return nil }

        let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
        // Source metadata is advisory. Reject excluded sources without trusting
        // a supplied source to allow captures from an excluded foreground app.
        let declaredSources = items.compactMap { item -> String? in
            guard item.types.contains(sourceType), let data = item.data(forType: sourceType),
                  data.count <= 512 else { return nil }
            return String(data: data, encoding: .utf8)
        }
        exclusion.update(from: settings)
        guard !exclusion.shouldExclude(observedBundleIdentifier: observedBundleIdentifier,
                                       declaredBundleIdentifiers: declaredSources) else { return nil }

        let filtered = filteredTypes(from: pbTypes)
        guard !filtered.isEmpty else { return nil }

        let clip = ClipEntry()
        clip.types = filtered.map(\.rawValue)
        var totalBytes = 0
        var rejected = false
        func boundedData(_ data: Data?, maximum: Int = ClipsService.maximumCaptureBytes) -> Data? {
            guard let data else { return nil }
            guard data.count <= maximum, data.count <= Self.maximumCaptureBytes - totalBytes else {
                rejected = true
                return nil
            }
            totalBytes += data.count
            return data
        }

        for pbType in filtered {
            switch pbType {
            case .string:
                if boundedData(pboard.data(forType: .string), maximum: Self.maximumTextBytes) != nil {
                    clip.stringValue = pboard.string(forType: .string)
                }
            case .rtfd:
                clip.rtfData = boundedData(pboard.data(forType: .rtfd))
                clip.isRTFD = true
            case .rtf:
                if clip.rtfData == nil {
                    clip.rtfData = boundedData(pboard.data(forType: .rtf))
                    clip.isRTFD = false
                }
            case .pdf:
                clip.pdfData = boundedData(pboard.data(forType: .pdf))
            case .fileURL:
                clip.filenames = items.compactMap {
                    guard boundedData($0.data(forType: .fileURL), maximum: Self.maximumTextBytes) != nil,
                          let value = $0.string(forType: .fileURL),
                          let url = URL(string: value), url.isFileURL else { return nil }
                    return url.path
                }
            case .URL:
                clip.urlStrings = items.compactMap {
                    guard boundedData($0.data(forType: .URL), maximum: Self.maximumTextBytes) != nil else { return nil }
                    return $0.string(forType: .URL)
                }
            case .tiff, .png:
                // Store actual TIFF bytes since capture normalizes image types
                // to TIFF; labelling raw PNG bytes as TIFF breaks other apps.
                if let tiff = boundedData(pboard.data(forType: .tiff)) {
                    guard Self.imageFitsCaptureLimits(tiff) else { return nil }
                    clip.imageData = tiff
                } else if !rejected, let png = boundedData(pboard.data(forType: .png)) {
                    guard Self.imageFitsCaptureLimits(png) else { return nil }
                    clip.imageData = boundedData(NSBitmapImageRep(data: png)?.tiffRepresentation)
                }
                if clip.imageData == nil {
                    Self.log.debug("Image type seen but no image bytes. pbTypes=\(filtered.map(\.rawValue).joined(separator: ","), privacy: .public)")
                } else {
                    Self.log.debug("Captured image bytes=\(clip.imageData?.count ?? 0, privacy: .public)")
                }
            default:
                break
            }
            if rejected { return nil }
        }

        // Lazy pasteboard providers can run while a representation is read.
        // Never save data assembled from different ownership generations.
        guard pboard.changeCount == changeCount else { return nil }
        return clip
    }

    static func imageFitsCaptureLimits(_ data: Data) -> Bool {
        guard let source = CGImageSourceCreateWithData(data as CFData,
                    [kCGImageSourceShouldCache: false] as CFDictionary),
              CGImageSourceGetCount(source) == 1,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [String: Any],
              let width = properties[kCGImagePropertyPixelWidth as String] as? NSNumber,
              let height = properties[kCGImagePropertyPixelHeight as String] as? NSNumber else { return false }
        let w = width.int64Value
        let h = height.int64Value
        return w > 0 && h > 0 && w <= 16_384 && h <= 16_384
            && w <= Int64(maximumImagePixels) / h
    }

    private func filteredTypes(from pbTypes: [NSPasteboard.PasteboardType]) -> [NSPasteboard.PasteboardType] {
        var results: [NSPasteboard.PasteboardType] = []

        for pbType in pbTypes {
            guard shouldStore(pbType) else { continue }

            if pbType == .tiff || pbType == .png {
                if !results.contains(.tiff) {
                    results.append(.tiff)
                }
                continue
            }

            results.append(pbType)
        }

        return results
    }

    /// Clears, then writes. A failed write puts the previous contents back.
    private func writeReplacingContents(_ items: [NSPasteboardItem], on pboard: NSPasteboard) -> Bool {
        let backup = (pboard.pasteboardItems ?? []).map { item in
            item.types.compactMap { type in
                item.data(forType: type).map { (type, $0) }
            }
        }
        pboard.clearContents()
        if pboard.writeObjects(items) { return true }
        let restored = backup.map { pairs -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in pairs { item.setData(data, forType: type) }
            return item
        }
        if !restored.isEmpty {
            pboard.writeObjects(restored)
        }
        return false
    }

    private func shouldStore(_ type: NSPasteboard.PasteboardType) -> Bool {
        guard let typeName = legacyTypeName(for: type) else { return false }
        return settings.storeTypes[typeName] ?? false
    }

    private func legacyTypeName(for type: NSPasteboard.PasteboardType) -> String? {
        switch type {
        case .string: return "String"
        case .rtf: return "RTF"
        case .rtfd: return "RTFD"
        case .pdf: return "PDF"
        case .fileURL: return "Filenames"
        case .URL: return "URL"
        case .tiff, .png: return "TIFF"
        default: return nil
        }
    }

    func clearAll() async throws {
        guard let context else { return }
        HistoryErasure.begin()
        // Invalidate queued monitor observations and remove the most recent
        // copy too; otherwise clearing history still leaves it available to paste.
        pasteboard.clearContents()
        monitor.ignoreCurrentChange()
        let all = try context.fetch(FetchDescriptor<ClipEntry>())
        for entry in all {
            // Views and delayed menu actions may still retain these objects.
            entry.stringValue = nil
            entry.rtfData = nil
            entry.pdfData = nil
            entry.imageData = nil
            entry.filenames = nil
            entry.urlStrings = nil
            entry.types = []
            context.delete(entry)
        }
        try context.save()
        context.undoManager?.removeAllActions()
        try HistoryErasure.compactStore(in: context)
    }

    func clearHistoryWithConfirmation() async {
        if settings.showAlertBeforeClearHistory {
            let alert = NSAlert()
            alert.messageText = "Clear History"
            alert.informativeText = "Delete all saved clipboard history and empty the current clipboard? Your snippets will be kept. Copies in backups or other apps cannot be removed."
            alert.addButton(withTitle: "Clear")
            alert.addButton(withTitle: "Cancel")
            guard alert.runModal() == .alertFirstButtonReturn else { return }
        }
        do {
            try await clearAll()
        } catch {
            let alert = NSAlert()
            alert.alertStyle = .critical
            alert.messageText = "History could not be fully cleared"
            alert.informativeText = error.localizedDescription
            alert.addButton(withTitle: "OK")
            alert.runModal()
        }
    }

    /// Writes a plain string to the pasteboard and triggers paste.
    @discardableResult
    func copyStringToPasteboard(_ string: String, pasteImmediately: Bool = true) async -> Bool {
        let pboard = pasteboard
        pboard.clearContents()
        guard pboard.setString(string, forType: .string) else { return false }
        if pasteImmediately && settings.autoPasteAfterSelection {
            Self.log.debug("Auto-paste after snippet selection is ON (immediate)")
            await paste.paste()
        } else {
            Self.log.debug("Snippet copied without immediate paste (pasteImmediately=\(pasteImmediately, privacy: .public), setting=\(self.settings.autoPasteAfterSelection, privacy: .public))")
        }
        return true
    }
}
